version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - MAPS_KEY=${MAPS_KEY}
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

